export const Routes = {
  Login: { path: "/login" },
  Signup: { path: "/sign-up" },
  Dashboard: { path: "/" },
  Blog: { path: "/blog" },
  PaymentSuccess: { path: "/payment-success" },
  Cart: { path: "/cart" },
  About: { path: "/about-us" },
  Checkout: { path: "/checkout" },
  Portfolio: { path: "/portfolio" },
  Shop: { path: "/shop" },
  ShopDetails: { path: "/shop-detail/:id" },
  SinglePortfolio: { path: "/single-portfolio" },
  SinglePost: { path: "/single-post/:id" },
  Profile: { path: "/profile" },
  Contact: {path: "/contact"},
  Order: {path: "/order"},
  OrderDetail: {path: "/order/detail"},
  ForgotPassword: {path: "/forgot-password"},
  NewPassword: {path: "/change-password"},
}